name: AutoDeploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: Node环境
        uses: actions/setup-node@v2
        with:
          node-version: 19

      - uses: pnpm/action-setup@v2
        name: 安装pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: 安装依赖
        if: steps.cache-hit.outputs.cache-hit != 'true'
        run: pnpm install

      - name: 打包构建
        run: pnpm run build:client && pnpm run build:server && zip -r client.zip ./dist/client && zip -r server.zip ./dist/server

      - name: 上传
        uses: actions/upload-artifact@v4
        with: 
            name: build
            path: |
              client.zip
              server.zip
